# styles.py

# This contains all the QSS (Qt Style Sheets) for our application.

MAIN_WINDOW_STYLE = "background-color: #161B22;"

CHAT_DISPLAY_STYLE = """
    QTextBrowser { 
        background-color: #0D1117; 
        color: #C9D1D9; 
        border: 1px solid #30363D; 
        border-radius: 6px; 
        font-family: 'Segoe UI', sans-serif; 
        font-size: 14px; 
        padding: 15px; 
    }
    a { 
        color: #58A6FF; 
    }
"""

TERMINAL_DISPLAY_STYLE = """
    QTextBrowser { 
        background-color: #010409; 
        color: #A6ACCD; 
        border: 1px solid #30363D; 
        border-radius: 6px; 
        font-family: 'Fira Code', 'Courier New', monospace;
        font-size: 12px;
        padding: 10px;
    }
"""

INPUT_BOX_STYLE = """
    QLineEdit { 
        background-color: #0D1117; 
        color: #C9D1D9; 
        border: 1px solid #30363D; 
        border-radius: 6px; 
        padding: 10px; 
    } 
    QLineEdit:focus { 
        border: 1px solid #58A6FF; 
    }
"""

LISTEN_BUTTON_STYLE = """
    QPushButton { 
        background-color: #21262D; 
        color: #C9D1D9; 
        border: 1px solid #30363D; 
        border-radius: 20px; 
    } 
    QPushButton:hover { 
        background-color: #30363D; 
    }
"""

LISTENING_BUTTON_STYLE = "background-color: #D24242;"

# --- NEW: Style for Code Blocks ---
# This style will be applied to the HTML generated by Pygments.
CODE_BLOCK_STYLE = """
    <style>
        pre {
            background-color: #010409;
            border: 1px solid #30363D;
            border-radius: 5px;
            padding: 10px;
            margin: 5px 0;
            white-space: pre-wrap;
            font-family: 'Fira Code', monospace;
        }
    </style>
"""